
name: Ship js Manual Prepare
on: deployment
jobs:
  manual_prepare:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-node@master
      - run: yarn install
      - run: |
            git config --global user.email "sys.gdp@globis.co.jp"
            git config --global user.name "sys-gdp"
      - run: yarn release:prepare -- --yes --no-browse
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
